name: Rotate Tailscale secret

on:
    schedule:
        # Run at midnight on the first day of the month
        # Every month
        - cron: '0 0 1 * *'

jobs:
    rotate:
        name: Rotate Tailscale secret
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.11'

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Rotate Tailscale secret
              env:
                DOPPLER_TOKEN: ${{ secrets.DOPPLER_SERVICE_TOKEN }}
                PROJECT: ${{ secrets.PROJECT }}
                CONFIG: ${{ secrets.CONFIG }}
              run: python main.py