name: Rotate Tailscale secret

on:
    push:
        branches: [main]

jobs:
    rotate:
        name: Rotate Tailscale secret
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.11'

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Rotate Tailscale secret
              run: python main.py